#!/usr/bin/python

import sys
import yaml
import tables
from cephalo_tools import filters
from numpy import zeros, mean, array, random, shape, size, nan, ma, isnan
from cephalo_tools.megprocess import baseline, find_triggers
from cephalo_tools.epoch_rejection import reject_by_std_method, \
    reject_by_diff_method, reject_by_entropy
from cephalo_tools.utility import get_hemisphere, save_table

class Configuration():
    def __init__(self):
        self.get_config()
    
    def get_config(self):
        """Gets the the configuration file. Asks for one if one is not specified
        at the command line."""
        try:
            config_file = sys.argv[1]
        except IndexError:
            config_file = raw_input(
                "No configuration file specified. Specify one now: ")
        
        self.parse_config(config_file)
        
    
    def parse_config(self, config_file):
        """Parses the configuration file. Makes many class attributes."""
        stream = open(config_file, 'r')
        config = yaml.load(stream)
    
        # Set default experiment name.
        if 'name' in config:
            self.name = config['name']
        else:
            self.name = "Untitled MEG experiment"
    
        # Set default experimenter name
        if 'experimenter' in config:    
            self.experimenter = config['experimenter']
        else:
            self.experimenter = "Anonymous Experimenter"
    
        # Set default data directory.
        if 'data_directory' in config:
            self.data_directory = config['data_directory']
        else:
            self.data_directory = "."
            
        if 'output_directory' in config:
            self.output_directory = config['output_directory']
        else:
            self.output_directory = "output/"
    
        # Set epochs
        if 'epoch_pre' not in config:
            self.epoch_pre = 100
            print "epoch_pre unspecified. Setting to 100."
        else:
            self.epoch_pre = config['epoch_pre']
    
        if 'epoch_post' not in config:
            self.epoch_post = 500
            print "epoch_post unspecified. Setting to 500."
        else:
            self.epoch_post = config['epoch_post']
    
        if 'expected_epochs' not in config:
            self.expected_epochs = 100
            print "expected_epochs unspecified. Setting to 100."
        else:
            self.expected_epochs = config['expected_epochs']
    
        # Load condition lists.
        
        if 'conditions' not in config:
            raise ValueError("No conditions are specified.")
        
        self.conditions = config['conditions']
        self.trigger_channels = sorted(self.conditions.keys())
        self.num_of_conditions = len(self.trigger_channels)
    
        if 'subjects' not in config or config['subjects'] == {}:
            raise ValueError("No subjects specified.")
        else:
            self.subjects = config['subjects']
            
        if 'sampling_frequency' in config:
            self.sampling_frequency = config['sampling_frequency']
        else:
            self.sampling_frequency = 1000
            print "No sampling frequency specified. Setting to 1000Hz."
            
        if 'lowpass_frequency' in config:
            self.lowpass_frequency = config['lowpass_frequency']
        else:
            self.lowpass_frequency = 20
            print "No lowpass frequency specified. Setting to 20Hz."
            

class Model():
    """Controls the flow of data."""
    
    def __init__(self, config):
        self.config = config
    
    def process(self, subject):
        """Implements the various steps of the processing chain."""
        
        print "Working on", subject, "..."
        data = Data(subject, self.config)
        
        # Lowpass the data
        data.lowpass()
        
        # Epoch data
        data.epoch("raw_data")
        data.epoch("lowpass_data")
        
        # Automatic epoch rejection
        data.reject_epochs(method="diff")
        
        # Compute mean epochs
        data.mean_epochs()
                
        #data.h5_file.close()
        
        return data
        
    def analyze(self):
        """Loops through subjects to process them."""
        self.data = [self.process(subject) for subject in self.config.subjects]

class View():
    """Controls data output."""
    
    def __init__(self, model):
        self.model = model
    
    def data_table(self, data_sets):
        """Outputs a text table."""
        
        print "Outputting table ..."
        out = "subject condition sample channel value hemisphere_x\n"
        for data in data_sets:
            data.mean_epochs = array(data.mean_epochs)
            conditions, samples, channels = shape(data.mean_epochs)
        
            for condition in xrange(conditions):
                for sample in xrange(samples):
                    for channel in xrange(channels):
                        true_channel = data.channels_of_interest[channel]
                        out += "%s c%d %d ch%d %f %s\n" % (
                                data.subject, 
                                condition+1, 
                                sample-self.model.config.epoch_pre, 
                                true_channel, 
                                data.mean_epochs[condition, sample, channel],
                                get_hemisphere(true_channel, axis='x'),
                                )
                        
            return out
    
    def print_table(self, data_sets):
        """Writes a table to disk."""
        
        number_of_factors = len(self.model.config.conditions.items()[0][1])
        out = "subject condition sample channel hemisphere_x hemisphere_y "
        out += ' '.join(["factor" + str(f) for f in range(number_of_factors)])
        out += " amplitude\n"
            
        for data in data_sets:
            table = data.h5_file.root.epochsTable.iterrows()
            for row in table:
                if row['hemisphere_x']:
                    hemisphere_x = "right"
                else:
                    hemisphere_x = "left"
                    
                if row['hemisphere_y']:
                    hemisphere_y = "posterior"
                else:
                    hemisphere_y = "anterior"
                
                out += "%s c%d %d ch%d %s %s %s %f\n" % \
                    (row['subject'], 
                    row['condition'], 
                    row['sample'], 
                    row['channel'], 
                    hemisphere_x, 
                    hemisphere_y,  
                    ' '.join(self.model.config.conditions[self.model.config.trigger_channels[row['condition']-1]]),
                    row['amplitude'])
        return out
                
    
    def to_table(self, data_sets):
        """Creates a pytables Table."""
        
        for data in data_sets:
            if "/epochsTable" in data.h5_file:
                data.h5_file.root.epochsTable.remove()
            
            table = data.h5_file.createTable(
                        where='/',
                        name='epochsTable',
                        description=Sample,
                        expectedrows=size(data.mean_epochs),
                        filters=tables.Filters(2)
                        )
                        
            data.mean_epochs = array(data.mean_epochs)
            conditions, samples, channels = shape(data.mean_epochs)
        
            sample_row = table.row
            for condition in xrange(conditions):
                for sample in xrange(samples):
                    for channel in xrange(channels):
                        sample_row['subject'] = data.subject
                        sample_row['condition'] = condition+1
                        sample_row['sample'] = \
                            sample-self.model.config.epoch_pre
                        sample_row['channel'] = \
                            data.channels_of_interest[channel]
                        sample_row['hemisphere_x'] = \
                            get_hemisphere(channel, axis='x', boolean=True)
                        sample_row['hemisphere_y'] = \
                            get_hemisphere(channel, axis='y', boolean=True)
                        sample_row['amplitude'] = \
                            data.mean_epochs[condition, sample, channel]
                        sample_row.append()
            
            table.flush()
                                
        
class Sample(tables.IsDescription):
    subject   = tables.StringCol(16)
    condition = tables.UInt8Col()
    sample    = tables.Int16Col()
    channel   = tables.UInt8Col()
    amplitude = tables.Float32Col()
    hemisphere_x = tables.BoolCol() # Left is True, Right is False
    hemisphere_y = tables.BoolCol() # Anterior is True, Posterior is False


class Experiment():
    def __init__(self):
        
        # Models
        self.config = Configuration()
        self.model = Model(self.config)
        
        self.model.analyze()
        
        # Views
        self.view = View(self.model)
        self.view.to_table(self.model.data)
        
        output_filename = self.config.output_directory + '/' + \
            self.config.name + ".output.txt"
        #data_table = self.view.data_table(self.model.data)
        data_table = self.view.print_table(self.model.data)
        
        save_table(output_filename, data_table)
        
        
        
        #self.view.plot_mmf()
        


class Data(object):
    
    def __init__(self, subject, config):
        
        self.subject = subject
        self.config = config
        
        self.load_data()
        self.load_triggers()
        self.channels_of_interest = self.config.subjects[self.subject]
    
    def load_data(self):
        """Loads an H5 data file containing MEG data."""
        
        print "Loading data ..."
        self.h5_filename = self.config.data_directory + self.subject + ".h5"
        self.h5_file = tables.openFile(self.h5_filename, mode = "r+")
        
    
    def load_triggers(self):
        """Create and fill triggers VLArray. Allows for ragged rows."""
        if "/triggers" in self.h5_file:
            self.h5_file.root.triggers.remove()
            
        self.triggers = self.h5_file.createVLArray(
                       where=self.h5_file.root, 
                       name='triggers',
                       atom=tables.Int32Atom(),
                       filters=tables.Filters(2)
                       )
                       
        print "Finding triggers ..."
        raw_data = self.h5_file.root.raw_data
        trigger_channels = self.config.trigger_channels
        for trigger_set in find_triggers(raw_data, trigger_channels):
            self.triggers.append(trigger_set)
        
        self.triggers.flush()
        return True
    
    def lowpass(self):
        """Lowpass filters the data."""

        # Create CArray for lowpassed data.
        if "/lowpass_data" not in self.h5_file:
            
            lowpass_data = self.h5_file.createCArray(
                where=self.h5_file.root, 
                name='lowpass_data', 
                atom=tables.Float32Atom(), 
                shape=shape(self.h5_file.root.raw_data),
                filters=tables.Filters(2)
                )
        
            print "Filtering ..."
            for channel in range(157):
                self.h5_file.root.lowpass_data[channel] = \
                    filters.lowpass(self.h5_file.root.raw_data[channel] * \
                    self.h5_file.root.convfactor[channel], 
                    sampling_frequency=self.config.sampling_frequency, 
                    lowpass_frequency=self.config.lowpass_frequency) 
    
    
    def epoch(self, data_array, apply_baseline=True):
        """Pulls out the epochs from the long data file."""
        self.front_sensors = [0, 41, 42, 83, 84, 107, 106, 105, 
                                104, 103, 102, 101, 100, 62, 61, 24, 23]
        self.loaded_channels = self.front_sensors + self.channels_of_interest
        
        channels = self.loaded_channels
        conditions = self.config.num_of_conditions
        expected_epochs = self.config.expected_epochs
        stimulus_pre = self.config.epoch_pre
        stimulus_post = self.config.epoch_post
        triggers = self.h5_file.root.triggers
        
        self.epoch_length  = stimulus_pre + 1 + stimulus_post # Include 0 point.
        
        epochs = zeros((conditions, self.epoch_length, len(channels), \
            expected_epochs))
        
        for (channel_index, channel) in enumerate(channels):
            print "Epoching channel %s ..." % channel
            the_chan = self.h5_file.getNode('/', data_array)[channel][:]
            for condition in range(conditions): 
                epoch_indices = range(len(triggers[condition]))
                random.shuffle(epoch_indices)
                epoch_indices = epoch_indices[:expected_epochs]
                
                for index, time in enumerate(epoch_indices):
                    epoch_start = triggers[condition][time] - stimulus_pre
                    epoch_end   = triggers[condition][time] + stimulus_post
                    the_epoch = the_chan[range(epoch_start, epoch_end + 1)]
                    epochs[condition, :, channel_index, index] = the_epoch
        
        
        
        ## This should work in the next version of pytables. 
        ## Uses fancy indexing.   
        #for condition in conditions: 
        #    print "Epoching condition %s ..." % condition
        #    for t in range(max_epochs):
        #        epoch_start = triggers[condition][t] - stimulus_pre
        #        epoch_end   = triggers[condition][t] + stimulus_post
        #        the_epoch = data[channels][range(epoch_start, epoch_end + 1)]
        #        epochs[condition, :, :, t] = the_epoch
        
        if apply_baseline:
            epochs = baseline(epochs.copy(), self.config.epoch_pre)
            
        self.save_epochs(epochs, data_array)
        
    def save_epochs(self, epochs, name):
        """ This needs cleaning up to avoid repitition."""
            
        print "Saving epochs ..."
        print "Shape:", shape(epochs)
        
        array_name = name + "_epochs"
        if "/" + array_name in self.h5_file:
            self.h5_file.getNode('/', array_name).remove()
        
        print array_name
        self.h5_file.createCArray(
            where=self.h5_file.root, 
            name=array_name, 
            atom=tables.Float32Atom(), 
            shape=shape(epochs),
            filters=tables.Filters(2))
        
        self.h5_file.getNode('/', array_name)[:] = epochs
        
        print "Done saving ..."
    
    def reject_epochs(self, method="std"):
        """
        Takes a set of epochs: conditions x samples x channels x epochs and
        masks out the rejected data points.
        """
        raw_data_epochs = self.h5_file.root.raw_data_epochs[:]
        lowpass_data_epochs = self.h5_file.root.lowpass_data_epochs[:]
        
        if method == "std":
            print "Rejecting epochs using standard deviation method ..."
            reject_fn = reject_by_std_method
        elif method == "diff":
            print "Rejecting epochs using difference method ..."
            reject_fn = reject_by_diff_method
        elif method == "entropy":
            print "Rejecting epochs using entropy method ..."
            reject_fn = reject_by_entropy
        else:
            raise ValueError('Rejection method "%s" not available.' % method)
        
        for condition in range(self.config.num_of_conditions):
            accepted, rejected = reject_fn(raw_data_epochs[condition, ...])
        
            lowpass_data_epochs[condition, :, :, rejected] = nan
        
        lowpass_data_epochs = ma.masked_array(lowpass_data_epochs, \
            isnan(lowpass_data_epochs))
        
    def mean_epochs(self):
        """Computes mean epochs."""
        
        epochs = self.h5_file.root.lowpass_data_epochs[:]
        self.mean_epochs = zeros((self.config.num_of_conditions, \
            shape(epochs)[1], len(self.channels_of_interest)))    
        for condition in range(self.config.num_of_conditions):
            self.mean_epochs[condition, :, :] = \
                mean(epochs[condition, :, len(self.front_sensors):, :], 2)

if __name__ == "__main__":
    
    Experiment()

